var musicList = [
  {file: 'je_taime_tu_me_manques', title: 'je t\'aime, tu me manques', author: 'unnq', site: 'soundcloud.com/unnq'},
  {file: 'lpchip', title: 'Curvature', author: 'LPchip', site: 'lpchip.nl'},
  {file: 'maple', title: 'Maple', author: 'The Amplified Apple', site: 'soundcloud.com/theamplifiedapple'},
  {file: 'decembrr', title: 'Decembrr', author: 'VIAES', site: 'soundcloud.com/viaes'},
  {file: 'esplanade', title: 'Esplanade', author: 'James Magnum', site: 'soundcloud.com/jamesmagnum'},
  {file: 'something_to_live_for', title: 'Something To Live For', author: 'Chain Reaction', site: 'chainreactionmusic.com'},
  {file: 'delta', title: 'Delta', author: 'Face Of Bear', site: 'soundcloud.com/face-of-bear', volume: 1.3},
  {file: 'mellow', title: 'Mellow', author: 'Kasse', site: 'soundcloud.com/spacholi', volume: 0.5},
  {file: 'looking_for_pluto', title: 'Looking For Pluto', author: 'Benedikt', site: 'soundcloud.com/bendikhjaltason'},
  {file: 'afterglow', title: 'Afterglow', author: 'Maximus Quackhandle', site: 'soundcloud.com/maximusquackhandle'},
  {file: 'fever_dream', title: 'Fever Dream', author: 'Eli G and WPH', site: 'youtube.com/channel/UCB4FEwdbXwnwRPvBXY8BO7A', volume: 0.9},
  {file: 'what_the_night_did_to_you', title: 'What The Night Did To You', author: 'Drug Dealer', site: 'soundcloud.com/everbeast'},
  {file: 'synthetic_popz', title: 'Synthetic Popz', author: 'O.J.B.', site: 'soundcloud.com/ljohnson91-1', volume: 0.8},
  {file: 'preamble', title: 'Preamble (L)', author: 'Walrus Tales', site: 'walrustales.com', volume: 0.8},
  {file: 'good_news', title: 'Good News', author: 'Inside People', site: 'insidepeoplemusic.com'},
  {file: 'tone_town', title: 'Tone Town', author: 'Ishan S', site: 'youtube.com/channel/UCxpjs6EPRocamfPmAQWw4iQ'},
  {file: 'pleasantville', title: 'Pleasantville', author: 'Hybrid Junkie', site: 'soundcloud.com/daftmau569'},
  {file: 'julias_song', title: 'Julia\'s Song', author: 'K-o-m-o-d-o', site: 'k-o-m-o-d-o.bandcamp.com', volume: 0.8},
  {file: 'pay_careful_attention', title: 'Pay Careful Attention', author: 'The Tin Pans', site: 'thetinpans.bandcamp.com'},
  {file: 'black_dog', title: 'Black Dog', author: 'Hanray', site: 'soundcloud.com/hanray-1', volume: 0.7},
  {file: 'aug14_2008', title: 'Aug14-2008', author: 'Steven Danglis', site: 'soundcloud.com/steven-danglis'},
  {file: 'yosemite', title: 'Yosemite', author: 'James S. Reid', site: 'thelabrats.net'},
  {file: 'the_overview_of_space', title: 'the overview of space', author: 'tobi', site: 'tobiwan.bandcamp.com'},
  {file: 'patter', title: 'Patter', author: 'Heat Legend', site: 'soundcloud.com/heatlegendmusic'},
  {file: 'incandescence', title: 'Incandescence', author: 'Lachy', site: 'soundcloud.com/lstevprods', volume: 0.8},
  {file: 'yna', title: 'Yna', author: 'Ry JT', site: 'soundcloud.com/reble-t', volume: 1.5},
  {file: 'no_memory', title: 'No Memory', author: 'ShiggyBeatz', site: 'shiggybeatz.com', volume: 0.6},
  {file: 'short_journey_home', title: 'Short Journey Home', author: 'Slowowls', site: 'soundcloud.com/slowowls', volume: 1.5},
  {file: 'firebox', title: 'Firebox', author: 'Signal-to-Noise', site: 'findyoursignal.com'},
  {file: 'orgone_vapors', title: 'orgone vapors', author: 'ephen', site: 'soundcloud.com/ephenager'},

  // below this line the songs won't play in the adventure mode but will play in other modes
  {file: 'inertia_jungle', title: 'Inertia Jungle', author: 'Attik-Attak', site: 'soundcloud.com/attik-attack-1'},
  {file: 'suburban_lunacy', title: 'Suburban Lunacy', author: 'Ray AB', site: 'rayab.bandcamp.com'},
  {file: 'whereknow', title: 'whereknow', author: 'Rick Sparks', site: 'ricksparks.bandcamp.com'},
  {file: 'courting_for_puss', title: 'Courting for Puss', author: 'Adeus Senhor F.', site: 'soundcloud.com/adeussenhorf'},
  {file: 'geometry', title: 'Geometry', author: 'Tim Gerwing', site: 'lascaux21.com'},
  {file: 'trauma_and_torment_of_truth', title: 'Trauma and Torment of Truth', author: 'Kode of Bliss', site: 'soundcloud.com/kellybarnard'}

]
